# Generated by Django 2.2.6 on 2021-02-15 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(max_length=200, primary_key=True, serialize=False)),
                ('review_text', models.TextField(max_length=850, null=True)),
                ('brand_name', models.TextField(max_length=250, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(max_length=250, null=True)),
                ('sentiment', models.TextField(max_length=250, null=True)),
                ('intention', models.TextField(max_length=350, null=True)),
                ('aspect', models.TextField(max_length=150, null=True)),
                ('review', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='from_review_id', to='reviews.Reviews', verbose_name='review_id')),
            ],
        ),
    ]
