# Generated by Django 2.2.6 on 2021-02-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210215_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_text',
            field=models.TextField(max_length=850, null=True),
        ),
    ]
