# Generated by Django 2.2.6 on 2021-02-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210215_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrases',
            old_name='phrase',
            new_name='phrase_text',
        ),
    ]
