# Generated by Django 2.2.6 on 2021-02-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20210215_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='overall_sentiment',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
