# Generated by Django 2.2.6 on 2021-02-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thematic_tokens',
            fields=[
                ('token_id', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('token', models.TextField(max_length=50, null=True)),
                ('token_class', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
