# Generated by Django 2.2.6 on 2021-02-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negative_tokens',
            fields=[
                ('token_id', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('negative_token', models.TextField(max_length=50, null=True, unique=True)),
                ('token_count', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='thematic_tokens',
            name='token',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
