# Generated by Django 2.2.6 on 2021-02-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicons', '0003_auto_20210226_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment_tokens',
            name='token',
            field=models.TextField(max_length=50, null=True, unique=True),
        ),
    ]
